SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON I.ITEM_ID=T.ITEM_ID
WHERE I.ITEM_ID NOT IN(
    SELECT DISTINCT (IFNULL(PARENT_ITEM_ID, 0))
    FROM ITEM_TREE
    
)


ORDER BY ITEM_ID DESC