SELECT 
MONTH(START_DATE) AS MONTH,
CAR_ID,
COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE)>=8 AND MONTH(START_DATE)<=10 AND 
CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    where start_date>="2022-08-01" and start_date<"2022-11-01" 
    GROUP BY CAR_ID
    HAVING COUNT(*)>4
)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING RECORDS >0
ORDER BY MONTH, CAR_ID DESC
