-- 코드를 입력하세요
SELECT 
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES
    # DATE_FORMAT(SALES_DATE, "%Y-%m-%d")
FROM BOOK B
JOIN BOOK_SALES S ON B.BOOK_ID=S.BOOK_ID
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY CATEGORY
ORDER BY CATEGORY